# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v1.0.8
      with:
        # GitHub token
        token: ${{ github.token }}
        # Time in milliseconds after which to timeout and cancel the deployment (default: 10 minutes)
        timeout: 600000
        # Maximum number of status report errors before cancelling a deployment (default: 10)
        error_count: 10 # optional, default is 10
        # Time in milliseconds between two deployment status report (default: 5 seconds)
        reporting_interval: 5000 # optional, default is 5000
        # Name of the artifact to deploy
        artifact_name: dist/* # optional, default is github-pages
